# Generated by Django 2.1.1 on 2018-10-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('detail_description', models.TextField()),
                ('posting_date', models.DateTimeField()),
                ('header_image', models.ImageField(upload_to='header_image/')),
                ('fb_link', models.CharField(blank=True, max_length=500)),
                ('twiter_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
