# Generated by Django 2.1.2 on 2018-10-30 10:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181030_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='detail_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
