# Generated by Django 2.1.2 on 2018-10-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_companyabouts'),
        ('blog', '0003_auto_20181030_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='author_name',
        ),
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='about.Team'),
        ),
    ]
