# Generated by Django 2.1.2 on 2018-10-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogs_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
    ]
