# Generated by Django 2.1.2 on 2018-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181030_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='comments',
            field=models.ManyToManyField(to='blog.BlogComments'),
        ),
    ]
