# Generated by Django 2.1.1 on 2018-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('trainer_name', models.CharField(max_length=500)),
                ('course_fee', models.IntegerField(max_length=15)),
                ('shedule', models.CharField(max_length=500)),
                ('available_seats', models.IntegerField(max_length=10)),
                ('objectives', models.TextField()),
                ('eligibility', models.TextField()),
                ('courseoutline', models.TextField()),
                ('background_image', models.ImageField(upload_to='courses_imgs/')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
