# Generated by Django 2.1.1 on 2018-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181025_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='material',
            field=models.FileField(blank=True, upload_to='helpingmatrial/'),
        ),
        migrations.AddField(
            model_name='course',
            name='material_type',
            field=models.CharField(choices=[('video', 'VIDEO'), ('image', 'IMAGE'), ('youtube', 'YOUTUBE')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
