# Generated by Django 2.1.2 on 2018-10-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseoutline',
        ),
    ]
