# Generated by Django 2.1.1 on 2018-10-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
