# Generated by Django 2.1.1 on 2018-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='background_imgs/'),
        ),
    ]
