# Generated by Django 2.1.1 on 2018-10-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('qulification', models.TextField()),
                ('interest', models.TextField()),
                ('aims', models.TextField()),
                ('other', models.TextField()),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
            ],
        ),
    ]
